#include "About.h"

void About::process()
{
	cout << "        <div class=""content-wrapper"">\n"
        "            <div class=""profile-content-wrapper"">\n"
        "                <h1>Hi, thanks for visiting our site.</h1>\n"
        "                <p><h4>It is intended to develop an application that allows the enrollment of students from a UC in their respective shifts.<br>Hope you enjoy and follow on social media!</h4></p><br><br>\n"
        "            </div>\n"
        "            <div class=""profile-items-wrapper"">\n"
        "                <div class=""profile-item-wrapper"">\n"
        "                    <div class=""profile-img-background""><img src=""/projeto/images/profile/1.jpg""  height=""600""></div>\n"
        "                    <div class=""profile-subtitle"">Diogo Silvino</div>\n"
        "                    <div class=""profile-social-media"">\n"
        "                        <a href=""https://github.com/DiogoRoseira""><img src=""/projeto/images/logos/github.png""></a>\n"
        "                        <a href=""https://www.instagram.com/diogo_roseira/""><img src=""/projeto/images/logos/instagram.png""></a>\n"
        "                        <a href=""https://www.facebook.com/diogo.roseira.98/""><img src=""/projeto/images/logos/facebook.png""></a>\n"
        "                        <a href=""https://twitter.com/DiogoRoseira""><img src=""/projeto/images/logos/twitter.png""></a>\n"
        "                    </div>\n"
        "                </div>\n"
        "                <div class=""profile-item-wrapper"">\n"
        "                    <div class=""profile-img-background""><img src=""/projeto/images/profile/2.png""></div>\n"
        "                    <div class=""profile-subtitle"">João Peixoto</div>\n"
        "                    <div class=""profile-social-media"">\n"
        "                        <a href=""https://github.com/joaopeixoto13""><img src=""/projeto/images/logos/github.png""></a>\n"
        "                        <a href=""https://www.instagram.com/joaopeixoto_01/""><img src=""/projeto/images/logos/instagram.png""></a>\n"
        "                        <a href=""https://www.facebook.com/jony.peixoto.5/""><img src=""/projeto/images/logos/facebook.png""></a>\n"
        "                        <a href=""https://twitter.com/JoaoPeixoto_01""><img src=""/projeto/images/logos/twitter.png""></a>\n"
        "                    </div>\n"
        "                </div>\n"
        "                <div class=""profile-item-wrapper"">\n"
        "                    <div class=""profile-img-background""><img src=""/projeto/images/profile/3.png""></div>\n"
        "                    <div class=""profile-subtitle"">José Fernandes</div>\n"
        "                    <div class=""profile-social-media"">\n"
        "                        <a href=""https://github.com/Blyre""><img src=""/projeto/images/logos/github.png""></a>\n"
        "                        <a href=""https://www.instagram.com/blyre_/""><img src=""/projeto/images/logos/instagram.png""></a>\n"
        "                        <a href=""https://www.facebook.com/jose.fernades.081""><img src=""/projeto/images/logos/facebook.png""></a>\n"
        "                        <a href=""https://twitter.com/Blyre_""><img src=""/projeto/images/logos/twitter.png""></a>\n"
        "                    </div>\n"
        "                </div>\n"
        "                <div class=""profile-item-wrapper"">\n"
        "                    <div class=""profile-img-background""><img src=""/projeto/images/profile/4.png""></div>\n"
        "                    <div class=""profile-subtitle"">Constantino Sousa</div>\n"
        "                    <div class=""profile-social-media"">\n"
        "                        <a href=""https://github.com/Constantino12""><img src=""/projeto/images/logos/github.png""></a>\n"
        "                        <a href=""https://www.instagram.com/iamstins/""><img src=""/projeto/images/logos/instagram.png""></a>\n"
        "                        <a href=""https://www.facebook.com/tininho.sousa""><img src=""/projeto/images/logos/facebook.png""></a>\n"
        "                        <a href=""https://twitter.com/Iamstinss""><img src=""/projeto/images/logos/twitter.png""></a>\n"
        "                    </div>\n"
        "                </div>   \n"
        "            </div>\n"
        "        </div>\n"
        "    </div>\n"
        "</body>\n"
        "<!--Javascript Code-->\n"
        "<script>\n"
        "    const profileItems = document.querySelectorAll('.profile-item-wrapper')\n"
        "    profileItems.forEach(profileItem => {\n"
        "        profileItem.addEventListener('mouseover', () => {\n"
        "            profileItem.childNodes[1].classList.add('img-darken');\n"
        "        })\n"
        "        profileItem.addEventListener('mouseout', () => {\n"
        "            profileItem.childNodes[1].classList.remove('img-darken');\n"
        "        })\n"
        "    })\n"
        "</script>\n"
        "</html>\n";
}
