#include "Home.h"

void Home::process()
{
	cout <<  "        <div class=""container-wrapper"">\n"
        "            <div class=""portfolio-items-wrapper"">\n"
        "                <div class=""portfolio-item-wrapper"">\n"
        "                    <div class=""portfolio-img-background"" style=""background-image:url(/projeto/images/registration.jpg)""></div>\n"
        "                    <div class=""img-text-wrapper"">\n"
        "                        <div class=""logo-wrapper"">\n"
        "                            <img src=""/projeto/images/logos/regist.png"">\n"
        "                        </div>\n"
        "                        <div class=""subtitle""><a href=""http://localhost/projeto/ProjectoATC2.exe/register"">Click to Register</a></div>\n"
        "                    </div>\n"
        "                </div>\n"
        "                <div class=""portfolio-item-wrapper"">\n"
        "                    <div class=""portfolio-img-background"" style=""background-image:url(/projeto/images/book.jpg)""></div>\n"
        "                   \n"
        "                    <div class=""img-text-wrapper"">\n"
        "                        <div class=""logo-wrapper"">\n"
        "                            <img src=""/projeto/images/logos/booking.png"">\n"
        "                        </div>\n"
        "                        <div class=""subtitle""><a href=""http://localhost/projeto/ProjectoATC2.exe/booking"">Click to Booking</a></div>\n"
        "                    </div>\n"
        "                </div>\n"
        "                <div class=""portfolio-item-wrapper"">\n"
        "                    <div class=""portfolio-img-background"" style=""background-image:url(/projeto/images/genetate2.jpg)""></div>\n"
        "                    <div class=""img-text-wrapper"">\n"
        "                        <div class=""logo-wrapper"">\n"
        "                            <img src=""/projeto/images/logos/generate.png"">\n"
        "                        </div>\n"
        "                        <div class=""subtitle""><a href=""http://localhost/projeto/ProjectoATC2.exe/generate"">Click to Generate</a></div>\n"
        "                    </div>\n"
        "                </div> \n"
        "                \n"
        "                <div class=""portfolio-item-wrapper"">\n"
        "                    <div class=""portfolio-img-background"" style=""background-image:url(/projeto/images/delete2.jpg)""></div>\n"
        "                   \n"
        "                    <div class=""img-text-wrapper"">\n"
        "                        <div class=""logo-wrapper"">\n"
        "                            <img src=""/projeto/images/logos/delete.png"">\n"
        "                        </div>\n"
        "                        <div class=""subtitle""><a href=""http://localhost/projeto/ProjectoATC2.exe/delete"">Click to Delete</a></div>\n"
        "                    </div>\n"
        "                </div>\n"
        "            </div>\n"
        "        </div>\n"
        "    </div>\n"
        "</body>\n"
        "<script>\n"
        "    const portfolioItems = document.querySelectorAll('.portfolio-item-wrapper')\n"
        "    portfolioItems.forEach(portfolioItem => {\n"
        "        portfolioItem.addEventListener('mouseover', () => {\n"
        "           portfolioItem.childNodes[1].classList.add('img-darken');\n"
        "        })\n"
        "        portfolioItem.addEventListener('mouseout', () => {\n"
        "            portfolioItem.childNodes[1].classList.remove('img-darken');\n"
        "        })\n"
        "    })\n"
        "</script>\n"
        "</html>\n";
}
