#include "WebBooking.h"
#include "Context.h"
#include "HtmlPage.h"

void WebBooking::process()
{
	Context* context = Context::getInstance();
	if (context->getStudents().size() > 0 && context->getShiftsInfo().totalPlaces() > 0 && context->getShiftsInfo().totalPlaces() >= context->getStudents().size()) {
		cout << " <div class=""container-wrapper"">\n"
        "            <div class=""register-wrapper"">\n"
        "                <div class=""options-wrapper"">\n"
        "                    <div class=""option-wrapper""><a href=""http://localhost/projeto/ProjectoATC2.exe/BookingFile"">Insert one file with books</a></div>\n"
        "                    <div class=""option-wrapper""><a href=""http://localhost/projeto/ProjectoATC2.exe/BookingManual"">Make one book manually</a></div>\n"
        "                    <div class=""option-wrapper""><a href=""http://localhost/projeto/ProjectoATC2.exe/BookingFind"">Consult one book</a></div>\n"
        "                    <div class=""option-wrapper""><a href=""http://localhost/projeto/ProjectoATC2.exe/BookingRemove"">Remove one book</a></div>\n"
        "                    <div class=""option-wrapper""><a href=""http://localhost/projeto/ProjectoATC2.exe/BookingConsult"">Consult booking informations</a></div>\n"
        "                </div>\n"
        "            </div>\n"
        "        </div>\n"
        "        <br>\n"
        "        <div class=""slideshow-container"">\n"
        "            <div class=""mySlides fade"">\n"
        "               <div class=""numbertext"">1 / 10</div>\n"
        "               <img src=""/projeto/images/Animation/1.jpg"" style=""width:1920px"" height=""530px"">\n"
        "            </div>\n"
        "            <div class=""mySlides fade"">\n"
        "                <div class=""numbertext"">2 / 10</div>\n"
        "                <img src=""/projeto/images/Animation/2.jpg"" style=""width:1920px"" height=""530px"">\n"
        "            </div>\n"
        "            <div class=""mySlides fade"">\n"
        "                <div class=""numbertext"">3 / 10</div>\n"
        "                <img src=""/projeto/images/Animation/3.jpg"" style=""width:1920px"" height=""530px"">\n"
        "            </div>\n"
        "            <div class=""mySlides fade"">\n"
        "                <div class=""numbertext"">4 / 10</div>\n"
        "                <img src=""/projeto/images/Animation/4.jpg"" style=""width:1920px"" height=""530px"">\n"
        "            </div>\n"
        "            <div class=""mySlides fade"">\n"
        "                <div class=""numbertext"">5 / 10</div>\n"
        "                <img src=""/projeto/images/Animation/5.jpg"" style=""width:1920px"" height=""530px"">\n"
        "            </div>\n"
        "            <div class=""mySlides fade"">\n"
        "                <div class=""numbertext"">6 / 10</div>\n"
        "                <img src=""/projeto/images/Animation/6.jpg"" style=""width:1920px"" height=""530px"">\n"
        "            </div>\n"
        "            <div class=""mySlides fade"">\n"
        "                <div class=""numbertext"">7 / 10</div>\n"
        "                <img src=""/projeto/images/Animation/7.jpg"" style=""width:1920px"" height=""530px"">\n"
        "            </div>\n"
        "            <div class=""mySlides fade"">\n"
        "                <div class=""numbertext"">8 / 10</div>\n"
        "                <img src=""/projeto/images/Animation/8.jpg"" style=""width:1920px"" height=""530px"">\n"
        "            </div>\n"
        "            <div class=""mySlides fade"">\n"
        "                <div class=""numbertext"">9 / 10</div>\n"
        "                <img src=""/projeto/images/Animation/9.jpg"" style=""width:1920px"" height=""530px"">\n"
        "            </div>\n"
        "            <div class=""mySlides fade"">\n"
        "                <div class=""numbertext"">10 / 10</div>\n"
        "                <img src=""/projeto/images/Animation/10.jpg"" style=""width:1920px"" height=""520px"">\n"
        "            </div>\n"
        "        </div>\n"
        "        <div style=""text-align:center"">\n"
        "            <span class=""dot""></span> \n"
        "            <span class=""dot""></span> \n"
        "            <span class=""dot""></span> \n"
        "            <span class=""dot""></span> \n"
        "            <span class=""dot""></span> \n"
        "            <span class=""dot""></span> \n"
        "            <span class=""dot""></span> \n"
        "            <span class=""dot""></span> \n"
        "            <span class=""dot""></span> \n"
        "            <span class=""dot""></span> \n"
        "          </div>\n"
        "    </div>\n"
        "</body>\n"
        "<script type=""text/javascript"" src=""/projeto/test.js""></script>\n"
        "</html>\n";
		context->getBlocked() = true;
	}
	else 
        cout << HtmlPage::HtmlError("Error: Invalid configuration of Students/Shifts!");
}
